// system-tests/projects/runner-ct-specs/src/Errors.jsx
import React from 'react'

const Errors = ({ throwOnMount = false }) => {
  const one = (msg) => {
    two(msg)
  }

  const two = (msg) => {
    three(msg)
  }

  const three = (msg) => {
    throw new Error(msg)
  }

  if (throwOnMount) {
    one('mount error')
  }

  return (
    <div>
      <button
        onClick={() => one('sync error')}
        id="trigger-sync-error"
      >
        Sync Error
      </button>
      <button
        onClick={() => setTimeout(() => one('async error'), 100)}
        id="trigger-async-error"
      >
        Async Error
      </button>
      <button
        onClick={() => (async () => one('promise rejection'))()}
        id="trigger-unhandled-rejection"
      >
        Rejection
      </button>
    </div>
  )
}

export default Errors

// system-tests/project-fixtures/svelte/src/lib/Errors.svelte
<script>
  export let throwError = false

  if (throwError) {
    throw new Error('mount error')
  }

  const handleSyncError = () => {
    throw new Error('sync error')
  }
  const handleAsyncError = () => {
    setTimeout(() => {
      throw new Error('async error')
    }, 50)
  }
</script>

<main>
  <div>
    <button id="sync-error" on:click={handleSyncError}>Sync Error</button>
    <button id="async-error" on:click={handleAsyncError}>Async Error</button>
  </div>
</main>
