// system-tests/project-fixtures/angular/src/app/components/errors.ts
import { Component, effect, input } from '@angular/core'

@Component({
  selector: 'errors-component',
  template: `<div>
  <button id="sync-error" (click)="syncError()">Sync Error</button>
  <button id="async-error" (click)="asyncError()">Sync Error</button>
  </div>`,
})
export class ErrorsComponent {
  throwError = input<boolean>(false)

  constructor () {
    effect(() => {
      if (this.throwError()) {
        throw new Error('mount error')
      }
    })
  }

  syncError () {
    throw new Error('sync error')
  }

  asyncError () {
    setTimeout(() => {
      throw new Error('async error')
    })
  }
}

// system-tests/project-fixtures/svelte/src/lib/Errors.svelte
<script>
  export let throwError = false

  if (throwError) {
    throw new Error('mount error')
  }

  const handleSyncError = () => {
    throw new Error('sync error')
  }
  const handleAsyncError = () => {
    setTimeout(() => {
      throw new Error('async error')
    }, 50)
  }
</script>

<main>
  <div>
    <button id="sync-error" on:click={handleSyncError}>Sync Error</button>
    <button id="async-error" on:click={handleAsyncError}>Async Error</button>
  </div>
</main>
