// packages/springboard/src/components/DependencyItem.vue
<template>
  <li data-cy="dep" class="bg-blue-50 p-4">
    <p class="flex justify-between pb-2">
      <div class="text-md font-bold">
        {{ dependency.packageName }}
      </div>
      <a class="underline text-blue-800 text-sm">
        Learn more
      </a>
    </p>
    <p class="text-md">
      {{ dependency.description }}
    </p>
  </li>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue'
import { Dependency } from '../supportedFrameworks'

export default defineComponent({
  props: {
    dependency: {
      type: Object as PropType<Dependency>,
      required: true
    }
  },
})
</script>

// packages/springboard-react/src/components/DependencyItem.tsx
import * as React from 'react'

interface DependencyItemProps {
  dependency: {
    packageName: string
    description: string
  }
}

export const DependencyItem: React.FC<DependencyItemProps> = (props) => {
  return (
    <li data-cy="dep" className="bg-blue-50 p-4">
      <p className="flex justify-between pb-2">
        <div className="text-md font-bold">{props.dependency.packageName}</div>
        <a className="underline text-blue-800 text-sm">Learn more</a>
      </p>
      <p className="text-md">{props.dependency.description}</p>
    </li>
  )
}
