// packages/springboard/src/components/SelectWizard.vue
<template>
  <h2 class="text-xl text-left mb-4">
    Welcome! {{loading ? '' : result.app.cypressVersion}} What kind of tests would you like to run?
  </h2>

  <h2 class="text-xl text-left mb-4" v-if="!loading">
    Welcome! {{result.app.cypressVersion}} What kind of tests would you like to run?
  </h2>

  <div class="max-w-128 mx-auto my-0">
    <NewUserWelcome v-if="showNewUserFlow" @close="dismissNewUserWelcome" />
  </div>

  <div class="text-center">
    <RunnerButton
      v-for="testingType of testingTypes"
      :key="testingType"
      :testingType="testingType"
      :selected="selectedTestingType === testingType"
      @click="selectTestingType(testingType)"
    />
  </div>
</template>

<script lang="ts">
import gql from 'graphql-tag'
import { defineComponent, markRaw, computed } from "vue";
import { useStore } from "../store";
import { TestingType, testingTypes } from "../types/shared";
import RunnerButton from "./RunnerButton.vue";
import NewUserWelcome from "./NewUserWelcome.vue";
import { useQuery } from "@vue/apollo-composable";

export default defineComponent({
  components: {
    RunnerButton,
    NewUserWelcome,
  },

  setup() {
    const { result, loading, error, refetch } = useQuery(gql`
      {
        app {
          cypressVersion
        }
      }
    `)

    setInterval(() => {
      refetch()
    }, 500)

    const store = useStore();

    const selectTestingType = (testingType: TestingType) => {
      store.setTestingType(testingType);
    };

    const dismissNewUserWelcome = () => {
      store.setDismissedHelper(true);
    };

    return {
      loading,
      result,
      testingTypes: markRaw(testingTypes),
      selectTestingType,
      showNewUserFlow: computed(
        () => store.getState().firstOpen && !store.getState().hasDismissedHelper
      ),
      selectedTestingType: computed(() => store.getState().testingType),
      dismissNewUserWelcome,
    };
  },
});
</script>

// packages/springboard-react/src/components/SelectWizard.tsx
import React from 'react'
import { gql, useMutation, useQuery } from '@apollo/client'
import type { TestingType } from '../types/shared'
import { NewUserWelcome } from './NewUserWelcome'
import { RunnerButton } from './RunnerButton'
import { DismissNewUserWelcomeMutationDocument, SelectWizardQueryDocument } from '../generated/graphql'

interface SelectWizardProps {
  testingTypes: TestingType[]
  showNewUserFlow: boolean
  setTestingType?: any
  selectedTestingType: string | undefined
}

gql`
  query SelectWizardQuery {
    app {
      cypressVersion
    }
    wizard {
      showNewUserWelcome
    }
  }
`

gql`
  mutation DismissNewUserWelcomeMutation {
    wizardSetDismissedHelper {
      showNewUserWelcome
    }
  }
`

export const SelectWizard: React.FC<SelectWizardProps> = (props) => {
  const { data, loading, error } = useQuery(SelectWizardQueryDocument)
  const [dismissNewUserWelcome] = useMutation(DismissNewUserWelcomeMutationDocument)

  if (error) {
    return <div>{JSON.stringify(error)}</div>
  }

  if (loading) {
    return null
  }

  return (
    <>
      <h2 className="text-xl text-left mb-4">
        Welcome! What kind of tests would you like to run?
      </h2>

      <div className="max-w-128 mx-auto my-0">
        {data.wizard.showNewUserWelcome && <NewUserWelcome onClose={dismissNewUserWelcome} />}
      </div>

      <div className="text-center">
        {props.testingTypes.map((testingType, idx) => (
          <RunnerButton
            key={testingType}
            testingType={testingType}
            selected={props.selectedTestingType === testingType}
            onChange={props.setTestingType(testingType)}
          />
        ))}
      </div>
    </>
  )
}
