// packages/runner-shared/src/automation-element/index.tsx
import React from 'react'

interface AutomationElementProps {
  namespace: string
  randomString: string
}

export const AutomationElement: React.FC<AutomationElementProps> = ({
  namespace,
  randomString,
}) => {
  return (
    <div id={`${namespace}-string`} style={{ display: 'none' }}>
      {randomString}
    </div>
  )
}

// packages/app/src/runner/automation/AutomationElement.vue
<template>
  <div
    :id="automationElementId"
    style="display: none"
  >
    {{ runnerUiStore.randomString }}
  </div>
</template>

<script lang="ts" setup>
import { useRunnerUiStore } from '../../store'

const automationElementId = window.__CYPRESS_CONFIG__.namespace
const runnerUiStore = useRunnerUiStore()
</script>
